#include <stdint.h>
#include "class.h"
#include "op.h"

static struct {
	char *name;
	int   noperands;
} optab[] = {
	[NOP]             = { "nop",             0 },
	[ACONST_NULL]     = { "aconst_null",     0 },
	[ICONST_M1]       = { "iconst_m1",       0 },
	[ICONST_0]        = { "iconst_0",        0 },
	[ICONST_1]        = { "iconst_1",        0 },
	[ICONST_2]        = { "iconst_2",        0 },
	[ICONST_3]        = { "iconst_3",        0 },
	[ICONST_4]        = { "iconst_4",        0 },
	[ICONST_5]        = { "iconst_5",        0 },
	[LCONST_0]        = { "lconst_0",        0 },
	[LCONST_1]        = { "lconst_1",        0 },
	[FCONST_0]        = { "fconst_0",        0 },
	[FCONST_1]        = { "fconst_1",        0 },
	[FCONST_2]        = { "fconst_2",        0 },
	[DCONST_0]        = { "dconst_0",        0 },
	[DCONST_1]        = { "dconst_1",        0 },
	[BIPUSH]          = { "bipush",          1 },
	[SIPUSH]          = { "sipush",          2 },
	[LDC]             = { "ldc",             1 },
	[LDC_W]           = { "ldc_w",           2 },
	[LDC2_W]          = { "ldc2_w",          2 },
	[ILOAD]           = { "iload",           1 },
	[LLOAD]           = { "lload",           1 },
	[FLOAD]           = { "fload",           1 },
	[DLOAD]           = { "dload",           1 },
	[ALOAD]           = { "aload",           1 },
	[ILOAD_0]         = { "iload_0",         0 },
	[ILOAD_1]         = { "iload_1",         0 },
	[ILOAD_2]         = { "iload_2",         0 },
	[ILOAD_3]         = { "iload_3",         0 },
	[LLOAD_0]         = { "lload_0",         0 },
	[LLOAD_1]         = { "lload_1",         0 },
	[LLOAD_2]         = { "lload_2",         0 },
	[LLOAD_3]         = { "lload_3",         0 },
	[FLOAD_0]         = { "fload_0",         0 },
	[FLOAD_1]         = { "fload_1",         0 },
	[FLOAD_2]         = { "fload_2",         0 },
	[FLOAD_3]         = { "fload_3",         0 },
	[DLOAD_0]         = { "dload_0",         0 },
	[DLOAD_1]         = { "dload_1",         0 },
	[DLOAD_2]         = { "dload_2",         0 },
	[DLOAD_3]         = { "dload_3",         0 },
	[ALOAD_0]         = { "aload_0",         0 },
	[ALOAD_1]         = { "aload_1",         0 },
	[ALOAD_2]         = { "aload_2",         0 },
	[ALOAD_3]         = { "aload_3",         0 },
	[IALOAD]          = { "iaload",          0 },
	[LALOAD]          = { "laload",          0 },
	[FALOAD]          = { "faload",          0 },
	[DALOAD]          = { "daload",          0 },
	[AALOAD]          = { "aaload",          0 },
	[BALOAD]          = { "baload",          0 },
	[CALOAD]          = { "caload",          0 },
	[SALOAD]          = { "saload",          0 },
	[ISTORE]          = { "istore",          1 },
	[LSTORE]          = { "lstore",          1 },
	[FSTORE]          = { "fstore",          1 },
	[DSTORE]          = { "dstore",          1 },
	[ASTORE]          = { "astore",          1 },
	[ISTORE_0]        = { "istore_0",        0 },
	[ISTORE_1]        = { "istore_1",        0 },
	[ISTORE_2]        = { "istore_2",        0 },
	[ISTORE_3]        = { "istore_3",        0 },
	[LSTORE_0]        = { "lstore_0",        0 },
	[LSTORE_1]        = { "lstore_1",        0 },
	[LSTORE_2]        = { "lstore_2",        0 },
	[LSTORE_3]        = { "lstore_3",        0 },
	[FSTORE_0]        = { "fstore_0",        0 },
	[FSTORE_1]        = { "fstore_1",        0 },
	[FSTORE_2]        = { "fstore_2",        0 },
	[FSTORE_3]        = { "fstore_3",        0 },
	[DSTORE_0]        = { "dstore_0",        0 },
	[DSTORE_1]        = { "dstore_1",        0 },
	[DSTORE_2]        = { "dstore_2",        0 },
	[DSTORE_3]        = { "dstore_3",        0 },
	[ASTORE_0]        = { "astore_0",        0 },
	[ASTORE_1]        = { "astore_1",        0 },
	[ASTORE_2]        = { "astore_2",        0 },
	[ASTORE_3]        = { "astore_3",        0 },
	[IASTORE]         = { "iastore",         0 },
	[LASTORE]         = { "lastore",         0 },
	[FASTORE]         = { "fastore",         0 },
	[DASTORE]         = { "dastore",         0 },
	[AASTORE]         = { "aastore",         0 },
	[BASTORE]         = { "bastore",         0 },
	[CASTORE]         = { "castore",         0 },
	[SASTORE]         = { "sastore",         0 },
	[POP]             = { "pop",             0 },
	[POP2]            = { "pop2",            0 },
	[DUP]             = { "dup",             0 },
	[DUP_X1]          = { "dup_x1",          0 },
	[DUP_X2]          = { "dup_x2",          0 },
	[DUP2]            = { "dup2",            0 },
	[DUP2_X1]         = { "dup2_x1",         0 },
	[DUP2_X2]         = { "dup2_x2",         0 },
	[SWAP]            = { "swap",            0 },
	[IADD]            = { "iadd",            0 },
	[LADD]            = { "ladd",            0 },
	[FADD]            = { "fadd",            0 },
	[DADD]            = { "dadd",            0 },
	[ISUB]            = { "isub",            0 },
	[LSUB]            = { "lsub",            0 },
	[FSUB]            = { "fsub",            0 },
	[DSUB]            = { "dsub",            0 },
	[IMUL]            = { "imul",            0 },
	[LMUL]            = { "lmul",            0 },
	[FMUL]            = { "fmul",            0 },
	[DMUL]            = { "dmul",            0 },
	[IDIV]            = { "idiv",            0 },
	[LDIV]            = { "ldiv",            0 },
	[FDIV]            = { "fdiv",            0 },
	[DDIV]            = { "ddiv",            0 },
	[IREM]            = { "irem",            0 },
	[LREM]            = { "lrem",            0 },
	[FREM]            = { "frem",            0 },
	[DREM]            = { "drem",            0 },
	[INEG]            = { "ineg",            0 },
	[LNEG]            = { "lneg",            0 },
	[FNEG]            = { "fneg",            0 },
	[DNEG]            = { "dneg",            0 },
	[ISHL]            = { "ishl",            0 },
	[LSHL]            = { "lshl",            0 },
	[ISHR]            = { "ishr",            0 },
	[LSHR]            = { "lshr",            0 },
	[IUSHR]           = { "iushr",           0 },
	[LUSHR]           = { "lushr",           0 },
	[IAND]            = { "iand",            0 },
	[LAND]            = { "land",            0 },
	[IOR]             = { "ior",             0 },
	[LOR]             = { "lor",             0 },
	[IXOR]            = { "ixor",            0 },
	[LXOR]            = { "lxor",            0 },
	[IINC]            = { "iinc",            2 },
	[I2L]             = { "i2l",             0 },
	[I2F]             = { "i2f",             0 },
	[I2D]             = { "i2d",             0 },
	[L2I]             = { "l2i",             0 },
	[L2F]             = { "l2f",             0 },
	[L2D]             = { "l2d",             0 },
	[F2I]             = { "f2i",             0 },
	[F2L]             = { "f2l",             0 },
	[F2D]             = { "f2d",             0 },
	[D2I]             = { "d2i",             0 },
	[D2L]             = { "d2l",             0 },
	[D2F]             = { "d2f",             0 },
	[I2B]             = { "i2b",             0 },
	[I2C]             = { "i2c",             0 },
	[I2S]             = { "i2s",             0 },
	[LCMP]            = { "lcmp",            0 },
	[FCMPL]           = { "fcmpl",           0 },
	[FCMPG]           = { "fcmpg",           0 },
	[DCMPL]           = { "dcmpl",           0 },
	[DCMPG]           = { "dcmpg",           0 },
	[IFEQ]            = { "ifeq",            2 },
	[IFNE]            = { "ifne",            2 },
	[IFLT]            = { "iflt",            2 },
	[IFGE]            = { "ifge",            2 },
	[IFGT]            = { "ifgt",            2 },
	[IFLE]            = { "ifle",            2 },
	[IF_ICMPEQ]       = { "if_icmpeq",       2 },
	[IF_ICMPNE]       = { "if_icmpne",       2 },
	[IF_ICMPLT]       = { "if_icmplt",       2 },
	[IF_ICMPGE]       = { "if_icmpge",       2 },
	[IF_ICMPGT]       = { "if_icmpgt",       2 },
	[IF_ICMPLE]       = { "if_icmple",       2 },
	[IF_ACMPEQ]       = { "if_acmpeq",       2 },
	[IF_ACMPNE]       = { "if_acmpne",       2 },
	[GOTO]            = { "goto",            2 },
	[JSR]             = { "jsr",             2 },
	[RET]             = { "ret",             1 },
	[TABLESWITCH]     = { "tableswitch",     OP_TABLESWITCH },
	[LOOKUPSWITCH]    = { "lookupswitch",    OP_LOOKUPSWITCH },
	[IRETURN]         = { "ireturn",         0 },
	[LRETURN]         = { "lreturn",         0 },
	[FRETURN]         = { "freturn",         0 },
	[DRETURN]         = { "dreturn",         0 },
	[ARETURN]         = { "areturn",         0 },
	[RETURN]          = { "return",          0 },
	[GETSTATIC]       = { "getstatic",       2 },
	[PUTSTATIC]       = { "putstatic",       2 },
	[GETFIELD]        = { "getfield",        2 },
	[PUTFIELD]        = { "putfield",        2 },
	[INVOKEVIRTUAL]   = { "invokevirtual",   2 },
	[INVOKESPECIAL]   = { "invokespecial",   2 },
	[INVOKESTATIC]    = { "invokestatic",    2 },
	[INVOKEINTERFACE] = { "invokeinterface", 4 },
	[INVOKEDYNAMIC]   = { "invokedynamic",   4 },
	[NEW]             = { "new",             2 },
	[NEWARRAY]        = { "newarray",        1 },
	[ANEWARRAY]       = { "anewarray",       2 },
	[ARRAYLENGTH]     = { "arraylength",     0 },
	[ATHROW]          = { "athrow",          0 },
	[CHECKCAST]       = { "checkcast",       2 },
	[INSTANCEOF]      = { "instanceof",      2 },
	[MONITORENTER]    = { "monitorenter",    0 },
	[MONITOREXIT]     = { "monitorexit",     0 },
	[WIDE]            = { "wide",            OP_WIDE },
	[MULTIANEWARRAY]  = { "multianewarray",  3 },
	[IFNULL]          = { "ifnull",          2 },
	[IFNONNULL]       = { "ifnonnull",       2 },
	[GOTO_W]          = { "goto_w",          4 },
	[JSR_W]           = { "jsr_w",           4 },
};

/* get number of operands of a given instruction */
int
op_getnoperands(U1 opcode)
{
	return optab[opcode].noperands;
}

/* get name of a given instruction */
char *
op_getname(U1 opcode)
{
	return optab[opcode].name;
}
